name: Firebase CI

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Use Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.2
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm i
    - run: npm install -g firebase-tools
    - run: npm run test
    - run: npm run build
    - name: Archive Build
      uses: actions/upload-artifact@v4.3.1
      with:
        name: build
        path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Download Build
        uses: actions/download-artifact@v4.1.2
        with:
          name: build
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}